name: New issue
description: Please review troubleshooting steps before submitting
body:
  - type: markdown
    attributes:
      value: |
        # 🔧 Troubleshooting Checklist

        Please go through the relevant section **before opening an issue**.
        Many common problems are resolved by these steps.

        ---

        ⚠️ **Known issue**: Installing on **Fedora** is currently problematic. It is recommended to use a **Debian-based** distribution or the **PSBBN Launcher for Windows**.

        1. Make sure you are running the latest version of your operating system and all available updates are installed
        2. Use a recommended OS. The **PSBBN Definitive Project** has been fully tested on:
        - Debian
        - Linux Mint
        - Raspberry Pi OS
        - Windows 10 Home Edition
        - Windows 11 Home Edition

        ## Problems Running the Script

        **If you are using [Windows](#installing-on-windows) and experience issues:**  

        If the PSBBN Definitive Project menu displays squares instead of text, or the Game Selector menu does not render correctly, change the PowerShell font. Right-click the PowerShell title bar, open **Properties**, and select **Cascadia Mono** (Windows 11) or **MS Gothic** (Windows 10). For other issues, continue with the troubleshooting steps below.

        1. Open PowerShell as an administrator and run the following command:
        ```
        wsl --unregister PSBBN
        ```
        2. Download the latest version of the `PSBBN-Launcher-For-Windows.ps1` script [here](https://github.com/CosmicScale/PSBBN-Definitive-English-Patch/releases/download/latest/PSBBN-Launcher-For-Windows.ps1)
        3. Ensure you have an active internet connection. If you are using a VPN, try disabling it
        4. Run the `PSBBN-Launcher-For-Windows.ps1` script again

        **If you are using Linux and experience issues:**
        1. Delete the `PSBBN-Definitive-Project` folder
        2. Re-Clone the repository with the following command:
        ```
        git clone https://github.com/CosmicScale/PSBBN-Definitive-Project.git
        ```

        **Still having issues?**
        1. Try connecting the PS2 drive directly to your PC using an internal SATA connection or a USB port directly on the motherboard. Avoid using add-on cards
        2. If you are using a SATA-to-USB adapter, try using a different make or model
        3. If you still have issues, try a different drive

        ## Problems Launching PSBBN and HOSDMenu
        When you connect the drive to your PS2 console and power it on, PSBBN or HOSDMenu should automatically launch.

        If your console boots to the regular OSD, freezes, or displays an error, you should try the following:
        1. Remove all PS2 Memory Cards from your console
        2. If you installed PSBBN, make sure you are using an **official Sony Network Adapter**; PSBBN does not support third-party HDD adapters
        3. Check that the connectors on the console and network or HDD adapter are clean and free of dust/debris
        4. Ensure the network or HDD adapter and drive are securely connected to the console
        5. If using a SATA mod, make sure it has been installed correctly
        6. Use a different drive and reinstall PSBBN or HOSDMenu
        7. If your console has an IDE converter or SATA mod installed, try using a different converter or mod.
        8. Use a different official Sony Network Adapter or third-party HDD adapter
        9. Use a different PS2 console

        ## Games Not Working
        Some games may fail to launch or exhibit compatibility issues. First, make sure your game image is a verified good dump. Check the MD5 or SHA-1 checksum of your `ISO` or `BIN` file and confirm that it matches the corresponding entry on [redump.org](http://redump.org/disc/16197/).

        For issues with PS2 games, if you selected OPL as your game launcher, you can check for existing issues or report a new one [here](https://github.com/ps2homebrew/Open-PS2-Loader/issues). If you selected NHDDL, you can do so [here](https://github.com/rickgaiser/neutrino/issues).

        If all PS1 or PS2 games fail to launch, follow the steps below:

        If you experience problems launching PS1 games, make sure you have correctly installed the **ATA BDM Assault drivers** on a PS2 Memory Card and that the card is inserted into your console. Installation instructions and a download link can be found [here](https://github.com/CosmicScale/PSBBN-Definitive-Project#installing-ata-bdm-assault).

        If games fail to launch from the Game Collection or Browser, try the following:
        1. If you have a mod chip, disable it
        2. If you're having trouble launching PS2 games, remove all PS2 Memory Cards from your console and try again. If this resolves the issue, delete any `Your System Configuration` save files from the memory cards, as corrupted configuration data can prevent games from launching.
        3. Check that the connectors on the console and Network or HDD Adapter are clean and free of dust or debris
        4. Ensure the Network or HDD adapter and drive are securely connected to the console
        5. If using a SATA mod, make sure it has been installed correctly

        If games still fail to launch, try loading PS2 games using OPL or NHDDL, and PS1 games using POPSLoader.

        If OPL freezes at startup, delete any existing OPL configuration files from your PS2 Memory Cards or connected USB devices. You can also hold `START` while OPL launches to bypass reading the configuration file.

        To display the games list in OPL, adjust the following settings:
        1. Settings > HDD (APA) Start Mode: Off
        2. Settings > BDM Start Mode: Auto
        3. Settings > BDM Devices > HDD (GPT/MBR): On
        4. Settings > Save Changes

        If PS2 games do not appear in the games list in NHDDL or OPL (after modifying the OPL settings as described above), or PS1 games do not appear in POPSLoader, try the following:
        1. Connect the PS2 drive directly to your PC using an internal SATA connection or a different SATA-to-USB adapter, then reinstall PSBBN or HOSDMenu
        2. Use a different drive and reinstall PSBBN or HOSDMenu
        3. If your console has an IDE converter or SATA mod installed, try using a different converter or mod
        4. Use a different official Sony Network Adapter or third-party HDD adapter
        5. Use a different PS2 console

        ---

        ✅ **If you have tried the relevant steps and the problem persists, check for an existing issue. If none exists, continue below to open a new issue.**  
        Please include all relevant log files:
        - `setup.log`
        - `PSBBN-installer.log`
        - `hosdmenu.log`
        - `game-installer.log`
        - `extras.log`
        - `media.log`

        **Linux** users can find these logs in `PSBBN-Definitive-Project/logs`. **Windows** users can find these logs in the folder where their games and media files are stored.

  - type: textarea
    id: issue
    attributes:
      label: Describe the issue
      description: Include relevant logs, OS, hardware details, and what you already tried.
    validations:
      required: true
